//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce_Web_App.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int PK_OrderId { get; set; }
        public string OrderDetail { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<int> FK_StatusId { get; set; }
        public string ShippingAddress { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> TotalBill { get; set; }
        public Nullable<int> FkPaymentMethodId { get; set; }
        public byte[] PaymentScreenShot { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}
