//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce_Web_App.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int PK_ProductId { get; set; }
        public string ProductName { get; set; }
        public string ArticalNo { get; set; }
        public string ProductColour { get; set; }
        public Nullable<int> FK_CategoryId { get; set; }
        public string ProductDetail { get; set; }
        public byte[] ProductImage { get; set; }
        public string ProductSize { get; set; }
        public Nullable<decimal> ProductBuyingPrice { get; set; }
        public Nullable<decimal> ProductSellingPrice { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
